---
abstract: 'Replace request base with value passed by HTTP proxy'
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  Catalyst::Runtime: 5.80007
  CatalystX::RoleApplicator: 0.005
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.910'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Request-ProxyBase
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  URI: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-TraitFor-Request-ProxyBase
version: 0.000005
