---
abstract: ~
author:
  - 'Tomas Doran (t0m) C<< <bobtfish@bobtfish.net> >>'
build_requires:
  Catalyst::Runtime: 5.80007
  CatalystX::RoleApplicator: 0.005
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Request-ProxyBase
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  URI: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bobtfish/catalyst-traitfor-request-proxybase
version: 0.000001
